kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: node-exporter-pvc-sys
  namespace: monitoring
  labels:
    apps: node-exporter
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: node-exporter-sys
  selector:
    matchLabels:
      name: node-exporter-hostpath-sys