kind: PersistentVolume
apiVersion: v1
metadata:
  name: node-exporter-pv-sys
  namespace: monitoring
  labels:
    apps: node-exporter
    name: node-exporter-hostpath-sys
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Delete
  storageClassName: node-exporter-sys
  hostPath:
    path: /data/pv004